//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use chrono::{DateTime, Local};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    pub role_id: i64,
    pub identity_code: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub sex: Option<String>,
    pub avatar: Option<String>,
    pub status: Option<String>,
    pub remark: Option<String>,
    pub created_at: Option<DateTime<Local>>,
    pub create_by: Option<i64>,
    pub updated_at: Option<DateTime<Local>>,
    pub update_by: Option<i64>,
    pub deleted_at: Option<DateTime<Local>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
