//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub name: String,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    pub role_id: Option<i64>,
    pub identity_code: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub sex: Option<String>,
    pub avatar: Option<String>,
    pub status: Option<String>,
    pub remark: Option<String>,
    pub created_at: Option<DateTime>,
    pub create_by: i64,
    pub updated_at: Option<DateTime>,
    pub update_by: i64,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
